version: '3.1'

services:
    mixpost:
        image: inovector/mixpost:latest
        ports:
            - 9000:80
        volumes:
            - mixpost-storage:/var/www/html/storage/app
            - mixpost-logs:/var/www/html/storage/logs
        depends_on:
            - mysql
            - redis  
    mysql:
        image: 'mysql/mysql-server:8.0'
        ports:
            - '3306:3306'
        volumes:
            - 'mixpost-mysql:/var/lib/mysql'
        healthcheck:
            test: ["CMD", "mysqladmin", "ping", "-p example_db_password"]
            retries: 3
            timeout: 5s
    redis:
        image: 'redis:latest'
        command: redis-server --appendonly yes --replica-read-only no --requirepass "example_redis_password"
        ports:
            - '6379:6379'
        volumes:
            - 'mixpost-redis:/data'
        healthcheck:
            test: ["CMD", "redis-cli", "ping"]
            retries: 3
            timeout: 5s
volumes:
    mixpost-mysql:
        driver: local
    mixpost-redis:
        driver: local
    mixpost-storage:
        driver: local
    mixpost-logs:
        driver: local
